# Generated by Django 2.1.7 on 2019-08-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0004_auto_20190521_1245'),
        ('helps_student', '0003_auto_20190419_1454'),
    ]

    operations = [
    ]
