# Generated by Django 2.1.7 on 2019-08-21 12:49

from django.db import migrations, models
import helps_student.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0005_merge_20190821_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='end_dates',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start_dates',
        ),
        migrations.AddField(
            model_name='workshop',
            name='days',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(default=helps_student.models.default_start_time),
        ),
        migrations.AddField(
            model_name='workshop',
            name='end_time',
            field=models.TimeField(default=helps_student.models.default_start_time),
        ),
        migrations.AddField(
            model_name='workshop',
            name='no_of_sessions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(default=helps_student.models.default_start_time),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_time',
            field=models.TimeField(default=helps_student.models.default_start_time),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='staff_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
