# Generated by Django 2.2.4 on 2019-10-06 09:29

from django.db import migrations, models
import helps_student.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0006_auto_20190821_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=helps_student.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=helps_student.models.default_start_time),
        ),
    ]
