# Generated by Django 2.2.4 on 2019-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0011_workshop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_files',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
