# Generated by Django 2.2.4 on 2019-10-10 12:47

import datetime
from django.db import migrations, models
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0014_auto_20191010_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='session_history',
            field=helps_admin.models.DateListField(blank=True, default=datetime.datetime.now),
        ),
    ]
