# Generated by Django 2.2.4 on 2019-10-10 12:48

import datetime
from django.db import migrations, models
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0015_auto_20191010_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='DOB',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='session_history',
            field=helps_admin.models.DateListField(default=datetime.datetime.now),
        ),
    ]
