# Generated by Django 2.2.4 on 2019-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0017_auto_20191010_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='staff_id',
            field=models.CharField(default=1, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='no_of_sessions',
            field=models.PositiveIntegerField(default=123),
        ),
    ]
