# Generated by Django 2.2.4 on 2019-10-10 13:29

from django.db import migrations, models
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0018_auto_20191011_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='best_contact_no',
            field=models.CharField(default='00', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='country_of_origin',
            field=models.CharField(default='placeholder', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='course',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='degree',
            field=models.CharField(default='placeholder', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='educational_background',
            field=models.CharField(default='placeholder', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='email',
            field=models.EmailField(default='utsemailplaceholder', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='faculty',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='first_language',
            field=models.CharField(default='placeholder', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='first_name',
            field=models.CharField(default='placeholder', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='gender',
            field=models.CharField(default='placeholder', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='last_name',
            field=models.CharField(default='placeholder', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='mobile',
            field=models.CharField(default='00', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='phone',
            field=models.CharField(default='00', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='preferred_first_name',
            field=models.CharField(default='firstnameplaceholder', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='session_history',
            field=helps_admin.models.DateListField(null=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='status',
            field=models.CharField(default='placeholder', max_length=64, null=True),
        ),
    ]
