# Generated by Django 2.1.11 on 2019-10-15 12:57


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0022_auto_20191011_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=500)),
                ('body', models.CharField(max_length=40000)),
                ('program', models.CharField(max_length=100)),
            ],
        ),
    ]
